### ISSUE TITLE
Plugin breaks some functions in PhpStorm 2016.1.2

### ISSUE THREAD

**Issue by nilsburg** [SeeSharpSoft/intellij-csv-validator#10]
Hi,
After installing the latest version of the CSV plugin in PhpStorm 2016.1.2 intentions stops working. The bulb stops showing and the Alt+Enter shortcut stops working as well.

Here is a entry from the log:
```
2018-03-21 09:57:53,195 [ 497514]  ERROR - aemon.impl.PassExecutorService - Either do the specified parameters not match any of the following constructors: [protected net.seesharpsoft.intellij.plugins.csv.intention.CsvShiftColumnLeftIntentionAction()] or the constructors were not accessible for 'class net.seesharpsoft.intellij.plugins.csv.intention.CsvShiftColumnLeftIntentionAction' 
org.picocontainer.PicoInitializationException: Either do the specified parameters not match any of the following constructors: [protected net.seesharpsoft.intellij.plugins.csv.intention.CsvShiftColumnLeftIntentionAction()] or the constructors were not accessible for 'class net.seesharpsoft.intellij.plugins.csv.intention.CsvShiftColumnLeftIntentionAction'
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:118)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:68)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.codeInsight.intention.IntentionActionBean.instantiate(IntentionActionBean.java:76)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getDelegate(IntentionActionWrapper.java:81)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFamilyName(IntentionActionWrapper.java:51)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFullFamilyName(IntentionActionWrapper.java:73)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.a(IntentionManagerSettings.java:129)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.isEnabled(IntentionManagerSettings.java:142)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentionActions(IntentionManagerImpl.java:260)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:302)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:201)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```
After uninstalling the plugin it works again.

**Comment by SeeSharpSoft** [comment]
Thanks for reporting - I will have look into this.

**Comment by SeeSharpSoft** [comment]
@nilsburg I will update the plugin in the JetBrains repository ASAP. Please re-open the issue in case you encounter the same error with the new [release 1.5.1](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.5.1). Thx!
