### ISSUE TITLE
Plugin crashed on load.

### ISSUE THREAD

**Issue by gbesch** [SeeSharpSoft/intellij-csv-validator#128]
After update, plugin crashed on startup when opening a second project in a new window.  The bug report submission option is not available for this plugin.  Trace inline below.

java.lang.NullPointerException
	at net.seesharpsoft.intellij.plugins.csv.CsvStorageHelper.getRelativeFileUrl(CsvStorageHelper.java:19)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.generateMapKey(CsvFileAttributes.java:40)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getFileSeparator(CsvFileAttributes.java:57)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvCodeStyleSettings.getCurrentSeparator(CsvCodeStyleSettings.java:68)
	at net.seesharpsoft.intellij.plugins.csv.CsvParserDefinition.createLexer(CsvParserDefinition.java:79)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvFileElementType.doParseContents(CsvFileElementType.java:23)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42)
	at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:127)
	at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:119)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.insertOuterElementsAndRemoveRanges(TemplateDataElementType.java:197)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.lambda$parseContents$0(TemplateDataElementType.java:96)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:562)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:94)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42)
	at com.intellij.lang.folding.CustomFoldingBuilder.isCustomFoldingRoot(CustomFoldingBuilder.java:216)
	at com.intellij.lang.folding.CustomFoldingBuilder.addCustomFoldingRegionsRecursively(CustomFoldingBuilder.java:77)
	at com.intellij.lang.folding.CustomFoldingBuilder.buildFoldRegions(CustomFoldingBuilder.java:42)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:246)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:226)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:192)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:50)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$4(AsyncEditorLoader.java:163)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$4(PsiDocumentManagerBase.java:507)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:505)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$5(AsyncEditorLoader.java:166)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:121)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.tryLoadEditor(AsyncEditorLoader.java:165)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$2(AsyncEditorLoader.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SeeSharpSoft** [comment]
Thanks for reporting. I could not reproduce it yet. Can you provide the IDE type and version you are using. Thanks!

**Comment by SeeSharpSoft** [comment]
Even though I couldn't reproduce the NullpointerException from the stack trace, I did include additional `null` checks for now. 🤞

**Comment by gbesch** [comment]
IDE is Rubymine.  I had a Rails project loaded in Rubymine and was actively working on it when I received the plugin update notice.  Upon relaunch after the update, Rubymine reported the plugin exception while loading the Rails project configuration file.  After disabling the plugin, the Rails project configuration loaded without issue.
I just now re-enabled the plugin and restarted Rubymine to ensure the issue is repeatable.  This time a second exception was reported and Rubymine suggests they may be related.  See traces inline below.
I'll be happy to provide further assistance in reproducing the issue.  This plugin is useful enough that I'd be very unhappy to have to uninstall it...
==================== First Exception Reported ===================java.lang.NullPointerException at net.seesharpsoft.intellij.plugins.csv.CsvStorageHelper.getRelativeFileUrl(CsvStorageHelper.java:19) at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.generateMapKey(CsvFileAttributes.java:40) at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getFileSeparator(CsvFileAttributes.java:57) at net.seesharpsoft.intellij.plugins.csv.settings.CsvCodeStyleSettings.getCurrentSeparator(CsvCodeStyleSettings.java:68) at net.seesharpsoft.intellij.plugins.csv.CsvParserDefinition.createLexer(CsvParserDefinition.java:79) at net.seesharpsoft.intellij.plugins.csv.psi.CsvFileElementType.doParseContents(CsvFileElementType.java:23) at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53) at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206) at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553) at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42) at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:127) at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:119) at com.intellij.psi.templateLanguages.TemplateDataElementType.insertOuterElementsAndRemoveRanges(TemplateDataElementType.java:197) at com.intellij.psi.templateLanguages.TemplateDataElementType.lambda$parseContents$0(TemplateDataElementType.java:96) at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:562) at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:94) at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206) at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553) at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42) at com.intellij.lang.folding.CustomFoldingBuilder.isCustomFoldingRoot(CustomFoldingBuilder.java:216) at com.intellij.lang.folding.CustomFoldingBuilder.addCustomFoldingRegionsRecursively(CustomFoldingBuilder.java:77) at com.intellij.lang.folding.CustomFoldingBuilder.buildFoldRegions(CustomFoldingBuilder.java:42) at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75) at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:246) at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:226) at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:192) at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:50) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$4(AsyncEditorLoader.java:163) at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$4(PsiDocumentManagerBase.java:507) at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974) at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57) at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:505) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$5(AsyncEditorLoader.java:166) at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:121) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151) at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.tryLoadEditor(AsyncEditorLoader.java:165) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$2(AsyncEditorLoader.java:122) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220) at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26) at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198) at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224) at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
================= Second Exception Reported ==================Following exceptions happened soon after this one, most probably they are induced.

2019-05-14T18:56:20.078java.lang.NullPointerException at net.seesharpsoft.intellij.plugins.csv.CsvStorageHelper.getRelativeFileUrl(CsvStorageHelper.java:19) at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.generateMapKey(CsvFileAttributes.java:40) at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getFileSeparator(CsvFileAttributes.java:57) at net.seesharpsoft.intellij.plugins.csv.settings.CsvCodeStyleSettings.getCurrentSeparator(CsvCodeStyleSettings.java:68) at net.seesharpsoft.intellij.plugins.csv.CsvParserDefinition.createLexer(CsvParserDefinition.java:79) at net.seesharpsoft.intellij.plugins.csv.psi.CsvFileElementType.doParseContents(CsvFileElementType.java:23) at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53) at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206) at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553) at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42) at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:127) at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:119) at com.intellij.psi.templateLanguages.TemplateDataElementType.insertOuterElementsAndRemoveRanges(TemplateDataElementType.java:197) at com.intellij.psi.templateLanguages.TemplateDataElementType.lambda$parseContents$0(TemplateDataElementType.java:96) at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:562) at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:94) at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206) at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553) at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254) at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42) at com.intellij.lang.folding.CustomFoldingBuilder.isCustomFoldingRoot(CustomFoldingBuilder.java:216) at com.intellij.lang.folding.CustomFoldingBuilder.addCustomFoldingRegionsRecursively(CustomFoldingBuilder.java:77) at com.intellij.lang.folding.CustomFoldingBuilder.buildFoldRegions(CustomFoldingBuilder.java:42) at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75) at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:246) at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:226) at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:192) at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:50) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$4(AsyncEditorLoader.java:163) at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$4(PsiDocumentManagerBase.java:507) at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974) at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57) at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:505) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$5(AsyncEditorLoader.java:166) at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:121) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151) at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.tryLoadEditor(AsyncEditorLoader.java:165) at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$2(AsyncEditorLoader.java:122) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220) at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26) at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198) at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224) at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

    

    On Tuesday, May 14, 2019, 1:47:48 AM EDT, GeeK <notifications@github.com> wrote:  
 
 
Thanks for reporting. I could not reproduce it yet. Can you provide the IDE type and version you are using. Thanks!

**Comment by SeeSharpSoft** [comment]
Got closed automatically due to merge - lets keep it open for now.

**Comment by cdesch** [comment]
Same Exception Occurring in Version `2.4.0`

**Comment by SeeSharpSoft** [comment]
@gbesch @cdesch Is the exception still occurring in the just released version 2.5.0?

**Comment by gbesch** [comment]
Exception does NOT occur in version 2.5.0.  THANKS!!!

Closing the issue...

**Comment by cdesch** [comment]
@SeeSharpSoft yes. The issue does not happen anymore. Thanks!
