### ISSUE TITLE
Plugin 2.12.0 Does not work with Android Studio 4.0

### ISSUE THREAD

**Issue by Zardozz** [SeeSharpSoft/intellij-csv-validator#232]
It causes Android Studio to lint not to work, picture below
![image](https://user-images.githubusercontent.com/13763054/85927801-5515ed80-b8a0-11ea-9304-b898ff686e57.png)

Disabling the plugin makes everything work correctly.

The hint says "Cannot resolve symbol 'LayoutInflater' and suggest to setup the JDK

Click setup JDK only offers 1.8.0_152 (so higher than 52 by 100)
![image](https://user-images.githubusercontent.com/13763054/85928610-20a53000-b8a6-11ea-9c9e-e67e80dcb659.png)

I have no other versions of Java installed

The settings say use inbuilt JRE  which is 1.8.0_242-release-1644-b01 amd64

It generates a number of IDE fatal errors one of them is below

`com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing 'com.intellij.psi.impl.cache.impl.id.IdIndexImpl'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:58)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2454)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:173)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:161)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:122)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.diagnostic.PluginException: While loading class net.seesharpsoft.intellij.plugins.psv.PsvFileType: net/seesharpsoft/intellij/plugins/psv/PsvFileType has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:223)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:474)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:464)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1207)
	at com.intellij.psi.impl.cache.impl.id.IdIndexImpl.getVersion(IdIndexImpl.java:25)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:349)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5300(FileBasedIndexImpl.java:107)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2448)
	... 12 more
Caused by: java.lang.UnsupportedClassVersionError: net/seesharpsoft/intellij/plugins/psv/PsvFileType has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:636)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:359)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:355)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	... 24 more`

Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: Statistic, org.jetbrains.kotlin, com.google.services.firebase, net.seesharpsoft.intellij.plugins.csv, pl.charmas.parcelablegenerator

**Comment by SeeSharpSoft** [comment]
Due to a new dependency introduced in version 2.11.0, the plugin requires a Java 9 (or higher). AFAIK there is no setting in the plugin.xml to define minimum requirements regarding the Java runtime to prevent unwanted plugin updates. I just updated the Readme to point out the new requirement with links to manual installation.

https://github.com/SeeSharpSoft/intellij-csv-validator/issues/207
