### ISSUE TITLE
Error with PyCharm Community

### ISSUE THREAD

**Issue by Virinas-code** [SeeSharpSoft/intellij-csv-validator#238]
I get this error with JetBrains PyCharm Community Edition 2019.1.1 ( CSV Plugin 2.9.3) when I insert :

> sa

Can you resolve it ?
```
java.lang.NullPointerException
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.generateCsv(CsvTableEditor.java:168)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.generateCsv(CsvTableEditorSwing.java:488)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.saveChanges(CsvTableEditor.java:129)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.storeStateChange(CsvTableEditor.java:123)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.storeStateChange(CsvTableEditorSwing.java:431)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorChangeListener.tableChanged(CsvTableEditorChangeListener.java:72)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(Unknown Source)
	at java.desktop/javax.swing.table.DefaultTableModel.setValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.setValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.editingStopped(Unknown Source)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.MultiLineCellRenderer.fireStopCellEditing(MultiLineCellRenderer.java:173)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.MultiLineCellRenderer.stopCellEditing(MultiLineCellRenderer.java:159)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.removeCellEditor(JBTable.java:674)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.hideNotify(JBTable.java:608)
	at com.intellij.util.ui.update.UiNotifyConnector.hideNotify(UiNotifyConnector.java:77)
	at com.intellij.util.ui.update.UiNotifyConnector.lambda$hierarchyChanged$0(UiNotifyConnector.java:63)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Virinas-code** [comment]
I get this other errors :
```
java.lang.NullPointerException
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.getFixedHeaderValues(CsvTableEditorSwing.java:446)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.getTableComponentData(CsvTableEditorSwing.java:464)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.storeStateChange(CsvTableEditorSwing.java:431)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.storeCurrentState(CsvTableEditorSwing.java:427)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.lambda$initializedUIComponents$2(CsvTableEditorSwing.java:120)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
and
```
java.lang.NullPointerException
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.generateCsv(CsvTableEditor.java:168)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.generateCsv(CsvTableEditorSwing.java:488)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.saveChanges(CsvTableEditor.java:129)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.updateTableComponentData(CsvTableEditor.java:93)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.api.TableActions.undoLastAction(TableActions.java:27)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorActionListeners.lambda$new$0(CsvTableEditorActionListeners.java:19)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by SeeSharpSoft** [comment]
@Virinas-code Thanks for reporting!

I tested with version 2019.1.3, created a new CSV file, switched to table editor and entered `sa` without any issues. Can you provide some detailed steps on how to reproduce it? Also try to upgrade to the latest minor version of PyCharm Community 2019.1 or even switch to a newer major version, there is no further development of this plugin for versions prior 2019.3.

**Comment by Virinas-code** [comment]
> 
> 
> @Virinas-code Thanks for reporting!
> 
> I tested with version 2019.1.3, created a new CSV file, switched to table editor and entered `sa` without any issues. Can you provide some detailed steps on how to reproduce it? Also try to upgrade to the latest minor version of PyCharm Community 2019.1 or even switch to a newer major version, there is no further development of this plugin for versions prior 2019.3.

@SeeSharpSoft Thank you.
The problem is resolved by an update.
