### ISSUE TITLE
crash when read file content like:  888888	food	 145	{"abc":"ccc","tips":"hello"}	

### ISSUE THREAD

**Issue by fearless-me** [SeeSharpSoft/intellij-csv-validator#283]
ava.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 1
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.calculateDistributedColumnWidths(CsvTableEditor.java:373)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.adjustAllColumnWidths(CsvTableEditor.java:350)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.selectNotify(CsvTableEditor.java:238)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$1.selectionChanged(EditorTabbedContainer.java:98)
	at com.intellij.ui.tabs.impl.JBTabsImpl.fireSelectionChanged(JBTabsImpl.java:1309)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:1264)
	at com.intellij.ui.tabs.impl.JBTabsImpl$9.run(JBTabsImpl.java:1217)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$1(EditorTabbedContainer.java:110)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$2(EditorTabbedContainer.java:108)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:1213)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:1203)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$EditorTabs.select(EditorTabbedContainer.java:696)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.setSelectedIndex(EditorTabbedContainer.java:145)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setSelectedEditor(EditorWindow.java:511)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:576)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:1016)

**Comment by SeeSharpSoft** [comment]
@fearless-me Thanks for reporting! However, I can't reproduce it myself locally. Can you please provide any more information, and provide an example inline marked as code. Like
\`\`\`
888888 food 145 {"abc":"ccc","tips":"hello"}
\`\`\`
results into
```
888888 food 145 {"abc":"ccc","tips":"hello"}
```

This provided example content is not valid CSV, whatever kind of separator is chosen. And this is how the table editor reacts for me:
![image](https://user-images.githubusercontent.com/3205800/116366967-2392e900-a807-11eb-95f2-643afbb968dc.png)

Did you also get this information on the table editor additionally to the error? What kind of separator did you choose? Do you have any editor settings that are not default?

**Comment by fearless-me** [comment]
@SeeSharpSoft yes ,I get the same information  in the 'Table Editor' mode
but I use tsv file. it woks fine at 'Text Mode'.

**Comment by fearless-me** [comment]
@SeeSharpSoft yes ,I get the same information  in the 'Table Editor' mode
but I use tsv file. it woks fine at 'Text Mode'.

**Comment by SeeSharpSoft** [comment]
> but I use tsv file. it woks fine in 'Text Mode'.

Thanks - that's good information. Does this also mean that there are tabs between the values in your example?
I already added an additional check for `calculateDistributedColumnWidth` in case of erroneous data (5e270b9f6bd61f75c075d742314d4bb64f86b15b). Now I will also double check the behavior with TSV files.

PS: Even though the file content is shown in Text Mode, it still is invalid CSV/TSV format, and features of the text editor might not be available or work properly.

**Comment by fearless-me** [comment]
@SeeSharpSoft yes, there are tabs between the values in my example, thx  for your great job.

**Comment by 1255542159** [comment]
I also have this problem,the table editor reacts for me:
![image](https://user-images.githubusercontent.com/33306650/117600624-de63a500-b17e-11eb-94d8-b0824bc016d7.png)
when I open text,the text reacts for me
CsvTokenType.COMMA or CsvTokenType.CRLF expected, got ','

The version I used
IDEA:2021.1
CSV plugin :2.14.3

**Comment by SeeSharpSoft** [comment]
Is this still an issue, or did 5e270b9f6bd61f75c075d742314d4bb64f86b15b fix it?
