### ISSUE TITLE
Null pointer when using csv redering in Mardown documentation

### ISSUE THREAD

**Issue by pkernevez** [SeeSharpSoft/intellij-csv-validator#292]
Hi,

I'm using CSV rendering, ie 
\```csv
...csv content...
\```

In this case the plugin raises an error because it tries to access to the file path of the csv, but it doesn't exist:
java.lang.NullPointerException
	at net.seesharpsoft.intellij.plugins.csv.CsvStorageHelper.getRelativeFilePath(CsvStorageHelper.java:24)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.generateMapKey(CsvFileAttributes.java:81)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getFileAttribute(CsvFileAttributes.java:86)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getFileAttribute(CsvFileAttributes.java:104)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getValueSeparator(CsvFileAttributes.java:183)
	at net.seesharpsoft.intellij.plugins.csv.CsvHelper.getValueSeparator(CsvHelper.java:203)
	at net.seesharpsoft.intellij.plugins.csv.CsvHelper.getValueSeparator(CsvHelper.java:197)
	at net.seesharpsoft.intellij.plugins.csv.CsvLexerFactory.createLexer(CsvLexerFactory.java:34)
	at net.seesharpsoft.intellij.plugins.csv.CsvParserDefinition.createLexer(CsvParserDefinition.java:73)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvFileElementType.doParseContents(CsvFileElementType.java:23)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:567)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:242)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.keepTreeFromChameleoningBack(InjectionRegistrarImpl.java:407)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.parseFile(InjectionRegistrarImpl.java:685)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.createAndRegisterInjected(InjectionRegistrarImpl.java:255)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:220)
	at org.intellij.plugins.markdown.injection.CodeFenceInjector.getLanguagesToInject(CodeFenceInjector.kt:47)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:441)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:247)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:177)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:331)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$3(InjectedGeneralHighlightingPass.java:185)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by SeeSharpSoft** [comment]
Thanks for reporting! First time for me noticing that MD plugin re-uses other plugins formatter. That's great! But yeah... its a bug. 🐛

**Comment by SeeSharpSoft** [comment]
Resolved in v2.17.0
