### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by pedrombmachado** [SeeSharpSoft/intellij-csv-validator#305]
Dear SeeSharSoft team,
  This is the error that I am getting after updating the plugin on the latest version of Pycharm-Community.

CSV Plugin 2.17.1 - Change Notes
						FIX: Plugin not showing column at caret Ctr+F1 #300
						FIX: Past few versions of this plugin don't show colors #298

```
java.lang.ExceptionInInitializerError
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvLanguageCodeStyleSettingsProvider.getLanguage(CsvLanguageCodeStyleSettingsProvider.java:14)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.initNonReadSettings(CommonCodeStyleSettingsManager.java:106)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.getCommonSettingsMap(CommonCodeStyleSettingsManager.java:74)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.addLanguageSettings(CommonCodeStyleSettingsManager.java:275)
	at com.intellij.psi.codeStyle.CodeStyleSettings.registerCommonSettings(CodeStyleSettings.java:1213)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.lambda$registerLanguageSettings$3(CodeStyleSettingsManager.java:165)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.registerLanguageSettings(CodeStyleSettingsManager.java:165)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager$1.languageCodeStyleProviderAdded(CodeStyleSettingsManager.java:123)
	at com.intellij.psi.codeStyle.CodeStyleSettingsServiceImpl$2.extensionAdded(CodeStyleSettingsServiceImpl.java:33)
	at com.intellij.psi.codeStyle.CodeStyleSettingsServiceImpl$2.extensionAdded(CodeStyleSettingsServiceImpl.java:29)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:785)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:985)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:820)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:808)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:790)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:392)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.tryInstallWithoutRestart(PluginDownloader.java:351)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$0(PluginUpdateDialog.java:198)
	at com.intellij.openapi.updateSettings.impl.UpdateInstaller.installDownloadedPluginUpdates(UpdateInstaller.kt:113)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$1(PluginUpdateDialog.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'csv' is already registered: class net.seesharpsoft.intellij.plugins.csv.CsvLanguage
	at com.intellij.lang.Language.<init>(Language.java:84)
	at net.seesharpsoft.intellij.plugins.csv.CsvLanguage.<init>(CsvLanguage.java:10)
	at net.seesharpsoft.intellij.plugins.csv.CsvLanguage.<clinit>(CsvLanguage.java:7)
	... 51 more
```

**Comment by SeeSharpSoft** [comment]
Thanks for reporting! Unfortunately I can't reproduce this issue. 

The line `Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'csv' is already registered: class net.seesharpsoft.intellij.plugins.csv.CsvLanguage` looks suspicious though. Are you using any other CSV related plugins?

Another guess: To be compliant with IntelliJ plugin naming policy, I just recently renamed this plugin to "CSV" - it was "CSV Plugin" before. Do you have by any chance two different versions of this plugin installed? However, the internal identifier didn't change, so I wouldn't expect any issues with the renaming...
