### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by keleqnma** [SeeSharpSoft/intellij-csv-validator#320]
java.lang.NullPointerException
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.generateCsv(CsvTableEditor.java:176)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.generateCsv(CsvTableEditorSwing.java:493)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.saveChanges(CsvTableEditor.java:137)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditor.storeStateChange(CsvTableEditor.java:131)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorSwing.storeStateChange(CsvTableEditorSwing.java:436)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableEditorChangeListener.tableChanged(CsvTableEditorChangeListener.java:72)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:276)
	at java.desktop/javax.swing.table.DefaultTableModel.setValueAt(DefaultTableModel.java:679)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2730)
	at java.desktop/javax.swing.JTable.editingStopped(JTable.java:4728)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.MultiLineCellRenderer.fireStopCellEditing(MultiLineCellRenderer.java:173)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.MultiLineCellRenderer.stopCellEditing(MultiLineCellRenderer.java:159)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.removeCellEditor(JBTable.java:837)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.hideNotify(JBTable.java:771)
	at com.intellij.util.ui.update.UiNotifyConnector.hideNotify(UiNotifyConnector.java:68)
	at com.intellij.util.ui.update.UiNotifyConnector.lambda$hierarchyChanged$0(UiNotifyConnector.java:53)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by SeeSharpSoft** [comment]
Thanks for reporting! Can you provide any further information about the circumstances this error occurred? For Example:
- Did you edit a value in the table editor?
- Did you close the editor view?
- Did you create a new file?
- etc.

**Comment by SeeSharpSoft** [comment]
Closing due to inactivity
