### ISSUE TITLE
Plugin overload and crash

### ISSUE THREAD

**Issue by CarinaSchoppe** [SeeSharpSoft/intellij-csv-validator#331]
Freeze for 40 seconds
IDE KILLED! Sampled time: 32500ms, sampling rate: 100ms, GC time: 1526ms (4%), Class loading: 0%, cpu load: 4%

The stack is from the thread that was blocking EDT

com.intellij.diagnostic.Freeze
	at java.base@17.0.3/java.util.regex.Pattern$Neg.match(Pattern.java:5170)
	at java.base@17.0.3/java.util.regex.Pattern$GroupCurly.match0(Pattern.java:4584)
	at java.base@17.0.3/java.util.regex.Pattern$GroupCurly.match(Pattern.java:4535)
	at java.base@17.0.3/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base@17.0.3/java.util.regex.Pattern$Begin.match(Pattern.java:3672)
	at java.base@17.0.3/java.util.regex.Matcher.search(Matcher.java:1728)
	at java.base@17.0.3/java.util.regex.Matcher.find(Matcher.java:745)
	at net.seesharpsoft.commons.util.Tokenizer.findToken(Tokenizer.java:228)
	at net.seesharpsoft.intellij.plugins.csv.CsvSharpLexer.locateToken(CsvSharpLexer.java:243)
	at net.seesharpsoft.intellij.plugins.csv.CsvSharpLexer.getTokenType(CsvSharpLexer.java:179)
	at com.intellij.lang.impl.TokenSequence$Builder.performLexing(TokenSequence.java:119)
	at com.intellij.lang.impl.TokenSequence.performLexing(TokenSequence.java:69)
	at com.intellij.lang.impl.PsiBuilderImpl.performLexing(PsiBuilderImpl.java:188)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:161)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:115)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:33)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvFileElementType.doParseContents(CsvFileElementType.java:23)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:175)
	at com.intellij.psi.impl.source.tree.LazyParseableElement$$Lambda$2010/0x00000008014fcfe0.run(Unknown Source)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:174)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:226)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:126)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:33)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:246)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:228)
	at com.intellij.completion.ml.common.RecentPlacesFeatures$StoreRecentPlacesListener.tryFindElementAt(RecentPlacesFeatures.kt:94)
	at com.intellij.completion.ml.common.RecentPlacesFeatures$StoreRecentPlacesListener.access$tryFindElementAt(RecentPlacesFeatures.kt:37)
	at com.intellij.completion.ml.common.RecentPlacesFeatures$StoreRecentPlacesListener$recentPlaceAdded$1.run(RecentPlacesFeatures.kt:70)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission$$Lambda$1209/0x0000000800eaf610.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$1210/0x0000000800eb1218.run(Unknown Source)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$1212/0x0000000800eb1b30.compute(Unknown Source)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.ProgressManager$$Lambda$1213/0x0000000800eb2000.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:191)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$960/0x0000000800b936b0.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:611)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$669/0x000000080079b1e0.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:686)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:642)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission$$Lambda$1203/0x0000000800ea0230.run(Unknown Source)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base@17.0.3/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base@17.0.3/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.3/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.3/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

**Comment by SeeSharpSoft** [comment]
@PixelsDE Thanks for reporting! Can you provide the CSV in question?
