### ISSUE TITLE
[Automated Report] java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.myUncommittedActions" is null

### ISSUE THREAD

**Issue by illustudio** [SeeSharpSoft/intellij-csv-validator#361]
Message
---
<no message>

Stacktrace
---
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.myUncommittedActions" is null
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater.doAction(CsvPsiTreeUpdater.java:98)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater.replaceField(CsvPsiTreeUpdater.java:287)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.setValueAt(CsvTableModelBase.java:172)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.setValue(CsvTableModelBase.java:148)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableModelSwing.setValueAt(CsvTableModelSwing.java:82)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
	at java.desktop/javax.swing.JTable.editingStopped(JTable.java:4785)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.fireStopCellEditing(CsvMultiLineCellRenderer.java:158)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.stopCellEditing(CsvMultiLineCellRenderer.java:144)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.removeCellEditor(JBTable.java:859)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.hideNotify(JBTable.java:793)
	at com.intellij.util.ui.update.UiNotifyConnector.hideNotify(UiNotifyConnector.java:80)
	at com.intellij.util.ui.update.UiNotifyConnector.lambda$hierarchyChanged$0(UiNotifyConnector.java:61)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\WebStorm2022.2\plugins\CSVEditor, version=3.0.0-222, package=null, isBundled=false), packagePrefix=null, instanceId=90, state=active)

IDE
---
WebStorm (WS-222.4345.14)

**Comment by SeeSharpSoft** [comment]
Fix released in 3.0.1
