### ISSUE TITLE
[Automated Report] java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.

### ISSUE THREAD

**Issue by vinceyyyyyy** [SeeSharpSoft/intellij-csv-validator#387]
Message
---
<no message>

Stacktrace
---
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ANY
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteSafeContext(TransactionGuardImpl.java:151)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.<init>(RefreshSessionImpl.java:59)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.<init>(RefreshSessionImpl.java:65)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processEvents(RefreshQueueImpl.java:184)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.updateCaseSensitivityIfUnknown(VirtualDirectoryImpl.java:304)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:76)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:519)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:49)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:55)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:120)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.findByUrl(VirtualFileManagerImpl.java:372)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.findFileByUrl(VirtualFileManagerImpl.java:359)
	at com.intellij.lang.PerFileMappingsBase.ensureStateLoaded(PerFileMappingsBase.java:334)
	at com.intellij.lang.PerFileMappingsBase.getMappingInner(PerFileMappingsBase.java:131)
	at com.intellij.lang.PerFileMappingsBase.getConfiguredMapping(PerFileMappingsBase.java:105)
	at com.intellij.sql.psi.SqlLanguageSubstitutor.getSqlLanguageFromMapping(SqlLanguageSubstitutor.java:97)
	at com.intellij.sql.psi.SqlLanguageSubstitutor.getSqlLanguageFromFile(SqlLanguageSubstitutor.java:85)
	at com.intellij.sql.psi.SqlLanguageSubstitutor.getConfiguredSqlLanguageDialect(SqlLanguageSubstitutor.java:71)
	at com.intellij.sql.psi.SqlLanguageSubstitutor.getSqlLanguage(SqlLanguageSubstitutor.java:41)
	at com.intellij.sql.psi.SqlLanguageSubstitutor.getLanguage(SqlLanguageSubstitutor.java:36)
	at com.intellij.psi.LanguageSubstitutors.substituteLanguage(LanguageSubstitutors.java:58)
	at com.intellij.lang.LanguageUtil.getLanguageForPsi(LanguageUtil.java:48)
	at com.intellij.lang.LanguageUtil.getLanguageForPsi(LanguageUtil.java:30)
	at net.seesharpsoft.intellij.plugins.csv.CsvHelper.isCsvFile(CsvHelper.java:81)
	at net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider.acceptCsvFile(CsvFileEditorProvider.java:21)
	at net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider.accept(CsvFileEditorProvider.java:47)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.checkProvider(FileEditorProviderManagerImpl.kt:76)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.access$checkProvider(FileEditorProviderManagerImpl.kt:23)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$2$1.invoke(FileEditorProviderManagerImpl.kt:101)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$2$1.invoke(FileEditorProviderManagerImpl.kt:100)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:90)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:73)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:125)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda-1$lambda-0(cancellableReadAction.kt:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda-1(cancellableReadAction.kt:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:45)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:59)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:54)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:54)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:46)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invokeSuspend(InternalReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:23)
	at com.intellij.openapi.application.rw.PlatformReadActionSupport.executeReadAction(PlatformReadActionSupport.kt:24)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:51)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:19)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProvidersAsync(FileEditorProviderManagerImpl.kt:100)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$1.invokeSuspend(FileEditorProviderManagerImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2022.3\plugins\CSVEditor, version=3.0.1-223, package=null, isBundled=false), packagePrefix=null, instanceId=111, state=active)

IDE
---
PyCharm (PY-223.7571.203)

**Comment by SeeSharpSoft** [comment]
The failing code is outside of plugin code, the initial call to check for CSV file (`com.intellij.lang.LanguageUtil.getLanguageForPsi`) looks legit.

Seems to be a regression by IntelliJ introduced in 2022.3, multiple issue are open:

https://youtrack.jetbrains.com/issue/IDEA-303171/java.lang.Throwable-Write-unsafe-context-Model-changes-are-allowed-from-write-safe-contexts-only-at
https://youtrack.jetbrains.com/issue/IDEA-303439/java.lang.Throwable-Write-unsafe-context-Model-changes-are-allowed-from-write-safe-contexts-only-at
https://youtrack.jetbrains.com/issue/IDEA-303437/java.lang.Throwable-Write-unsafe-context-Model-changes-are-allowed-from-write-safe-contexts-only-at
https://youtrack.jetbrains.com/issue/IDEA-302379/Write-unsafe-context-assert-on-project-opening
