### ISSUE TITLE
[Automated Report] java.lang.NullPointerException: Cannot invoke "com.intellij.ide.plugins.IdeaPluginDescriptor.getVersion()" because the return value of "net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getPluginDescriptor()" is null

### ISSUE THREAD

**Issue by francisSM** [SeeSharpSoft/intellij-csv-validator#444]
Message
---
<no message>

Stacktrace
---
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.plugins.IdeaPluginDescriptor.getVersion()" because the return value of "net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getPluginDescriptor()" is null
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getVersion(CsvPlugin.java:27)
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.runActivity(CsvPlugin.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Ed1tor, id=net.seeshafrpsoft1.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.1.1, package=null, isBundled=false), packagePrefix=null, instanceId=90, state=active)

IDE
---
IntelliJ IDEA (IC-222.4554.10)

**Comment by SeeSharpSoft** [comment]
@francisSM ⚠️ Be careful, you installed a potential harmful plagiarism of this plugin - the plugin name of the plugin you are using is "CSV Ed`1`tor".⚠️

**Comment by rameee01** [comment]
Message
---
<no message>

Stacktrace
---
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.plugins.IdeaPluginDescriptor.getVersion()" because the return value of "net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getPluginDescriptor()" is null
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getVersion(CsvPlugin.java:27)
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.runActivity(CsvPlugin.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Ed1tor, id=net.seeshafrpsoft1.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.1.1, package=null, isBundled=false), packagePrefix=null, instanceId=91, state=active)

IDE
---
IntelliJ IDEA (IC-222.3739.54)

**Comment by rameee01** [comment]
Message
---
<no message>

Stacktrace
---
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.plugins.IdeaPluginDescriptor.getVersion()" because the return value of "net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getPluginDescriptor()" is null
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getVersion(CsvPlugin.java:27)
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.runActivity(CsvPlugin.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Ed1tor, id=net.seeshafrpsoft1.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.1.1, package=null, isBundled=false), packagePrefix=null, instanceId=91, state=active)

IDE
---
IntelliJ IDEA (IC-222.3739.54)

**Comment by Viktorija-Grietniece** [comment]
Message
---
<no message>

Stacktrace
---
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.plugins.IdeaPluginDescriptor.getVersion()" because the return value of "net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getPluginDescriptor()" is null
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getVersion(CsvPlugin.java:27)
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.runActivity(CsvPlugin.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Ed1tor, id=net.seeshafrpsoft1.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.1.1, package=null, isBundled=false), packagePrefix=null, instanceId=90, state=active)

IDE
---
IntelliJ IDEA (IC-222.4167.29)

**Comment by Viktorija-Grietniece** [comment]
Message
---
<no message>

Stacktrace
---
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.plugins.IdeaPluginDescriptor.getVersion()" because the return value of "net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getPluginDescriptor()" is null
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.getVersion(CsvPlugin.java:27)
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin.runActivity(CsvPlugin.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Ed1tor, id=net.seeshafrpsoft1.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.1.1, package=null, isBundled=false), packagePrefix=null, instanceId=90, state=active)

IDE
---
IntelliJ IDEA (IC-222.4167.29)
