### ISSUE TITLE
[Automated Report] com.intellij.diagnostic.PluginException: Element: class net.seesharpsoft.intellij.plugins.csv.psi.CsvFile #csv  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file://D:/OneDrive/01_Work/FoodPriceScraper/import_manager/7290875100001_v1_stores.csv, vFileId=236989, content=VirtualFileContent{size=1695}, eventSystemEnabled=true}(566e792b); com.intellij.psi.SingleRootFileViewProvider{vFile=file://D:/OneDrive/01_Work/FoodPriceScraper/import_manager/7290875100001_v1_stores.csv, vFileId=236989, content=VirtualFileContent{size=1695}, eventSystemEnabled=true}(51af699e)

### ISSUE THREAD

**Issue by haim248** [SeeSharpSoft/intellij-csv-validator#474]
Message
---
<no message>

Stacktrace
---
com.intellij.diagnostic.PluginException: Element: class net.seesharpsoft.intellij.plugins.csv.psi.CsvFile #csv  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file://D:/OneDrive/01_Work/FoodPriceScraper/import_manager/7290875100001_v1_stores.csv, vFileId=236989, content=VirtualFileContent{size=1695}, eventSystemEnabled=true}(566e792b); com.intellij.psi.SingleRootFileViewProvider{vFile=file://D:/OneDrive/01_Work/FoodPriceScraper/import_manager/7290875100001_v1_stores.csv, vFileId=236989, content=VirtualFileContent{size=1695}, eventSystemEnabled=true}(51af699e)
invalidated at: see attachment [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:99)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:482)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureValid(SmartPointerManagerImpl.java:112)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:82)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:75)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:70)
	at com.intellij.refactoring.suggested.UtilsKt.createSmartPointer(Utils.kt:39)
	at com.intellij.ide.navbar.impl.PsiNavBarItem.createPointer(DefaultNavBarItem.kt:139)
	at com.intellij.ide.navbar.ide.NavBarVmItemKt.toVmItems(NavBarVmItem.kt:50)
	at com.intellij.ide.navbar.ide.NavBarServiceKt.contextModelInner(NavBarService.kt:154)
	at com.intellij.ide.navbar.ide.NavBarServiceKt.access$contextModelInner(NavBarService.kt:1)
	at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:136)
	at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:135)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:92)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:91)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:126)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1$lambda$0(cancellableReadAction.kt:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1(cancellableReadAction.kt:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:45)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:91)
	at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:72)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:72)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class net.seesharpsoft.intellij.plugins.csv.psi.CsvFile #csv  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file://D:/OneDrive/01_Work/FoodPriceScraper/import_manager/7290875100001_v1_stores.csv, vFileId=236989, content=VirtualFileContent{size=1695}, eventSystemEnabled=true}(566e792b); com.intellij.psi.SingleRootFileViewProvider{vFile=file://D:/OneDrive/01_Work/FoodPriceScraper/import_manager/7290875100001_v1_stores.csv, vFileId=236989, content=VirtualFileContent{size=1695}, eventSystemEnabled=true}(51af699e)
invalidated at: see attachment
	... 44 more

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2023.1\plugins\CSVEditor, version=3.2.0-231, package=null, isBundled=false), packagePrefix=null, instanceId=93, state=active)

IDE
---
PyCharm (PY-231.9161.41)

**Comment by SeeSharpSoft** [comment]
Can you please provide any further information, e.g. when did this happen, what was the interaction with the file (e.g. open, edit, create), did it only happens once, etc.
