### ISSUE TITLE
[Automated Report] com.intellij.diagnostic.PluginException: Element: class net.seesharpsoft.intellij.plugins.csv.psi.CsvFile #csv  because: file://C:/Users/kacpe/Documents/Uczelnia/Inżynierka/personality-type-prediction-ops/static/csv/records_cleaned.csv (invalid) is invalid

### ISSUE THREAD

**Issue by BaranskiKacper** [SeeSharpSoft/intellij-csv-validator#752]
Message
---
<no message>

Stacktrace
---
com.intellij.diagnostic.PluginException: Element: class net.seesharpsoft.intellij.plugins.csv.psi.CsvFile #csv  because: file://C:/Users/kacpe/Documents/Uczelnia/Inżynierka/personality-type-prediction-ops/static/csv/records_cleaned.csv (invalid) is invalid
invalidated at: see attachment [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:99)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:467)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureValid(SmartPointerManagerImpl.java:110)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:80)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:74)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:57)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:64)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.convert(PsiElement2UsageTargetAdapter.java:177)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.convert(PsiElement2UsageTargetAdapter.java:171)
	at com.intellij.refactoring.BaseRefactoringProcessor.previewRefactoring(BaseRefactoringProcessor.java:285)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:256)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$16(BaseRefactoringProcessor.java:624)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:640)
	at com.intellij.refactoring.BaseRefactoringProcessor$2.actionPerformed(BaseRefactoringProcessor.java:478)
	at com.intellij.usages.impl.UsageViewImpl.doReRun(UsageViewImpl.java:1295)
	at com.intellij.usages.impl.UsageViewImpl.refreshUsages(UsageViewImpl.java:1281)
	at com.intellij.usages.impl.UsageViewImpl$MyPerformOperationRunnable.run(UsageViewImpl.java:2218)
	at com.intellij.usages.impl.UsageViewImpl$9.actionPerformed(UsageViewImpl.java:1727)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class net.seesharpsoft.intellij.plugins.csv.psi.CsvFile #csv  because: file://C:/Users/kacpe/Documents/Uczelnia/Inżynierka/personality-type-prediction-ops/static/csv/records_cleaned.csv (invalid) is invalid
invalidated at: see attachment
	... 67 more

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2023.2\plugins\CSVEditor, version=3.2.1-232, package=null, isBundled=false), packagePrefix=null, state=active)

IDE
---
PyCharm (PC-232.8660.197)

**Comment by SeeSharpSoft** [comment]
Need more input to investigate
