### ISSUE TITLE
[Automated Report] java.util.NoSuchElementException

### ISSUE THREAD

**Issue by RustamGiz** [SeeSharpSoft/intellij-csv-validator#785]
Message
---
<no message>

Stacktrace
---
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:970)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2710)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
	at java.desktop/java.awt.Container.findComponentAt(Container.java:2695)
	at java.desktop/java.awt.Container$1.findComponentAt(Container.java:273)
	at java.desktop/sun.awt.GlobalCursorManager._updateCursor(GlobalCursorManager.java:193)
	at java.desktop/sun.awt.GlobalCursorManager.updateCursorImmediately(GlobalCursorManager.java:95)
	at java.desktop/sun.awt.X11.XComponentPeer.updateCursorImmediately(XComponentPeer.java:695)
	at java.desktop/java.awt.Component.updateCursorImmediately(Component.java:3259)
	at java.desktop/java.awt.Container.validate(Container.java:1672)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.getTableCellRendererComponent(CsvMultiLineCellRenderer.java:93)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5812)
	at com.intellij.ui.table.JBTable.prepareRenderer(JBTable.java:731)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2210)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2112)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1908)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTable$MultiSpanCellTableUI.paint(CsvTable.java:119)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.table.JBTable.paintComponent(JBTable.java:428)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.table.JBTable.paint(JBTable.java:564)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:247)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1151)
	at java.desktop/javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1731)
	at java.desktop/javax.swing.JViewport.windowBlitPaint(JViewport.java:1684)
	at java.desktop/javax.swing.JViewport.setViewPosition(JViewport.java:1219)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.hsbStateChanged(BasicScrollPaneUI.java:1222)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1173)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:371)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:309)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:175)
	at java.desktop/javax.swing.JScrollBar.setValue(JScrollBar.java:486)
	at com.intellij.ui.components.DefaultScrollBarUI$Listener.setValueFrom(DefaultScrollBarUI.java:599)
	at com.intellij.ui.components.DefaultScrollBarUI$Listener.mouseDragged(DefaultScrollBarUI.java:476)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6705)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3403)
	at java.desktop/java.awt.Component.processEvent(Component.java:6426)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4600)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2023.3/CSVEditor, version=3.2.3-233, package=null, isBundled=false), packagePrefix=null, state=active)

IDE
---
PyCharm (PC-233.11799.298)

**Comment by SeeSharpSoft** [comment]
Require more details for investigation
