### ISSUE TITLE
[Automated Report] java.lang.Throwable: Cannot find element among its parent' children. element: 'CSV File'; parent: 'PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7'; children: [PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7/out, PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7/src, PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7/.idea, CSV File, CSV File, PsiFile(plain text):HW7.iml, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, GitIgnore file, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File];  file:CSV File

### ISSUE THREAD

**Issue by fan71c** [SeeSharpSoft/intellij-csv-validator#827]
Message
---
<no message>

Stacktrace
---
java.lang.Throwable: Cannot find element among its parent' children. element: 'CSV File'; parent: 'PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7'; children: [PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7/out, PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7/src, PsiDirectory:/Users/fant1c/Library/Mobile Documents/com~apple~CloudDocs/Universities/UPenn/CIT 5940/Coding/HW7/.idea, CSV File, CSV File, PsiFile(plain text):HW7.iml, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, GitIgnore file, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File, CSV File];  file:CSV File
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getChildIndex(SharedPsiElementImplUtil.java:113)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getNextSibling(SharedPsiElementImplUtil.java:89)
	at com.intellij.psi.impl.source.PsiFileImpl.getNextSibling(PsiFileImpl.java:334)
	at net.seesharpsoft.intellij.plugins.csv.inspection.CsvValidationInspection$1.visitElement(CsvValidationInspection.java:83)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:59)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:334)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:342)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:348)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:311)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:311)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:314)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:299)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:367)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:310)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:285)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:227)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.2/plugins/CSVEditor, version=3.3.0-232, package=null, isBundled=false), packagePrefix=null, state=active)

IDE
---
IntelliJ IDEA (IU-232.10227.8)

**Comment by SeeSharpSoft** [comment]
Calling `com.intellij.psi.impl.source.PsiFileImpl.getNextSibling(PsiFileImpl.java:334)`, which throws this error. Function call and input are valid.
