### ISSUE TITLE
Plugin exception on startup with Intellij 2024.2 and CSV 2.21.0

### ISSUE THREAD

**Issue by ilanKeshet** [SeeSharpSoft/intellij-csv-validator#858]
Plugin exception on startup with Intellij 2024.2 and CSV 2.21.0

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'net.seesharpsoft.intellij.plugins.csv.actions.CsvChangeEscapeCharacterActionGroup' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/463b1881-f3c7-43d3-ad6d-2e333533b4d6">

```
IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 6, 2024
Licensed to <Reducted>
Subscription is active until April 24, 2025.
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.5
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.20224.203)
  com.ultrahob.zerolength.plugin (0.95)
  artsiomch.meson.syntax (203.1.0)
  org.jetbrains.plugins.go (242.20224.300)
  com.tabnine.TabNine (1.115.0)
  com.intellij.grazie.pro (0.3.325)
  info.fluffos.idea_bison (20230902.02)
  ir.msdehghan.plugins.ansible (0.92)
  name.kropp.intellij.makefile (242.20224.155)
  org.ermadan.kafkalytic (0.10.5)
  org.intellij.plugins.hcl (242.20224.159)
  PythonCore (242.20224.300)
  aws.toolkit.core (3.21-242)
  com.jetbrains.space (242.20224.155)
  org.jetbrains.plugins.ruby (242.20224.300)
  org.jetbrains.plugins.go-template (242.20224.155)
  idea.goyacc (0.1.0)
  Pythonid (242.20224.300)
  com.koxudaxi.pydantic (0.4.14)
  com.intellij.ml.llm (242.20224.309)
  net.seesharpsoft.intellij.plugins.csv (2.21.0)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  mobi.hsz.idea.gitignore (4.5.3)
  com.intellij.bigdatatools.core (242.20224.300)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  org.intellij.scala (2024.2.20)
  amazon.q (3.21-242)
  com.google.idea.bazel.ijwb (2024.07.16.0.1-api-version-242)
  com.github.copilot (1.5.17.6356)
  aws.toolkit (3.21-242)
Kotlin: 242.20224.300-IJ
```

**Comment by eatobin** [comment]
Same problem - same config.

Also in GoLand:

GoLand 2024.2
Build #GO-242.20224.306, built on August 6, 2024

**Comment by SeeSharpSoft** [comment]
Just uploaded version 3.3.0 for IntelliJ platforms version 242, will be available after validation & approval.

**Comment by eatobin** [comment]
Appreciated!

**Comment by ilanKeshet** [comment]
Thank you  @SeeSharpSoft 🙏

**Comment by ilanKeshet** [comment]
The new version 3.4.0-242 works without errors 
Thank you @SeeSharpSoft 🥇

**Comment by SeeSharpSoft** [comment]
New CSV Editor version 4.* is available, bringing back the tabularize formatting of version 2.*
