### ISSUE TITLE
Exception when using plugin in IntelliJ IntelliJ IDEA 2024.2

### ISSUE THREAD

**Issue by s2k** [SeeSharpSoft/intellij-csv-validator#859]
About IntelliJ:

IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 6, 2024
Runtime version: 21.0.3+13-b509.4 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 16384M
Cores: 16
Non-Bundled Plugins:
…
  net.seesharpsoft.intellij.plugins.csv (2.21.0)
…
Kotlin: 242.20224.300-IJ

How I got to the behaviour:

* Updated IntelliJ to the version mentioned above.
* The CSV version is now 2.21.0 (sorry can't remember the previous version I had)

The Exception:

```java
java.lang.Throwable: net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings <clinit> requests com.intellij.openapi.editor.ex.EditorSettingsExternalizable instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.openapi.client.ClientSessionImpl.doGetService(ClientSessionImpl.kt:119)
	at com.intellij.openapi.client.ClientAwareComponentManager.postGetService(ClientAwareComponentManager.kt:45)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.openapi.editor.ex.EditorSettingsExternalizable.getInstance(EditorSettingsExternalizable.java:222)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings$OptionSet.<init>(CsvEditorSettings.java:90)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings.<init>(CsvEditorSettings.java:96)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings.<clinit>(CsvEditorSettings.java:38)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditorProvider.accept(CsvTableEditorProvider.java:40)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.checkProvider(FileEditorProviderManagerImpl.kt:270)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.access$checkProvider(FileEditorProviderManagerImpl.kt:1)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt$getProviderIfApplicable$2.invoke(FileEditorProviderManagerImpl.kt:242)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt$getProviderIfApplicable$2.invoke(FileEditorProviderManagerImpl.kt:241)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1$lambda$0(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1(cancellableReadAction.kt:29)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

**Comment by SeeSharpSoft** [comment]
Just uploaded version 3.3.0 for IntelliJ platforms version 242, will be available after validation & approval.
