### ISSUE TITLE
Exception on Rider 2024.3 EAP start

### ISSUE THREAD

**Issue by mat-kap** [SeeSharpSoft/intellij-csv-validator#868]
With the new Rider 2024.3 EAP and the Plugin 2.21.0 I get the following exception on every application start:

`java.lang.Throwable: net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings <clinit> requests com.intellij.openapi.editor.ex.EditorSettingsExternalizable instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1590)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1559)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:755)
	at com.intellij.openapi.client.ClientSessionImpl.doGetService$lambda$3(ClientSessionImpl.kt:119)
	at com.intellij.codeWithMe.ClientId$Companion.withExplicitClientId(ClientId.kt:262)
	at com.intellij.openapi.client.ClientSessionImpl.doGetService(ClientSessionImpl.kt:118)
	at com.intellij.openapi.client.ClientAwareComponentManager.postGetService(ClientAwareComponentManager.kt:45)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:699)
	at com.intellij.openapi.editor.ex.EditorSettingsExternalizable.getInstance(EditorSettingsExternalizable.java:223)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings$OptionSet.<init>(CsvEditorSettings.java:90)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings.<init>(CsvEditorSettings.java:96)
	at net.seesharpsoft.intellij.plugins.csv.settings.CsvEditorSettings.<clinit>(CsvEditorSettings.java:38)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableEditorProvider.accept(CsvTableEditorProvider.java:40)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.checkProvider(FileEditorProviderManagerImpl.kt:270)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.getProviderIfApplicable$lambda$1(FileEditorProviderManagerImpl.kt:242)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$3(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:321)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:29)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:43)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:39)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:61)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:28)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.getProviderIfApplicable(FileEditorProviderManagerImpl.kt:241)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.access$getProviderIfApplicable(FileEditorProviderManagerImpl.kt:1)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1$2.invokeSuspend(FileEditorProviderManagerImpl.kt:144)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1$2.invoke(FileEditorProviderManagerImpl.kt)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1$2.invoke(FileEditorProviderManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:74)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:43)
	at kotlinx.coroutines.TimeoutKt.withTimeout-KLykuaI(Timeout.kt:71)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
`

**Comment by CLOVIS-AI** [comment]
Same error with IntelliJ IDEA 2024.3 EAP (Ultimate Edition), Build #IU-243.15521.24, built on September 19, 2024.

**Comment by SeeSharpSoft** [comment]
CSV Editor v2.* is outdated. I'm preparing a new v4.0 which comes with the missing formatting features of v2 (aka tabularize), and will in general focusing more on text editor convenience.

**Comment by SeeSharpSoft** [comment]
Try updating to latest CSV Editor version 4.*
