### ISSUE TITLE
[Automated Report] com.intellij.diagnostic.PluginException: Cannot check provider net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider [Plugin: net.seesharpsoft.intellij.plugins.csv]

### ISSUE THREAD

**Issue by christoph2** [SeeSharpSoft/intellij-csv-validator#876]
Message
---
<no message>

Stacktrace
---
com.intellij.diagnostic.PluginException: Cannot check provider net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:29)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:277)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:234)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:498)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2024.2/plugins/CSVEditor, version=3.4.0-242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github/tracker, descriptorPath=intellij.vcs.github.tracker.xml, path=~/Applications/PyCharm Professional.app/Contents/plugins/vcs-github, version=242.22855.92, package=org.jetbrains.plugins.github.tasks, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github.ultimate/cron, descriptorPath=intellij.vcs.github.ultimate.cron.xml, path=~/Applications/PyCharm Professional.app/Contents/plugins/vcs-github, version=242.22855.92, package=com.intellij.vcs.github.ultimate.cron, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github.ultimate/docker, descriptorPath=intellij.vcs.github.ultimate.docker.xml, path=~/Applications/PyCharm Professional.app/Contents/plugins/vcs-github, version=242.22855.92, package=com.intellij.vcs.github.ultimate.action.runs.docker, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/Applications/PyCharm Professional.app/Contents/lib, version=242.22855.92, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/Applications/PyCharm Professional.app/Contents/lib, version=242.22855.92, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/Applications/PyCharm Professional.app/Contents/lib, version=242.22855.92, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/Applications/PyCharm Professional.app/Contents/lib, version=242.22855.92, package=null, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, descriptorPath=plugin.xml, path=~/Applications/PyCharm Professional.app/Contents/plugins/vcs-github, version=242.22855.92, package=com.intellij.vcs.github.ultimate, isBundled=true), )

IDE
---
PyCharm (PY-242.22855.92)

**Comment by elsteiner** [comment]
Message
---
Nothing

Stacktrace
---
com.intellij.diagnostic.PluginException: Cannot check provider net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:157)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:29)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:277)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:498)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
	at java.base/java.lang.Thread.run(Thread.java:1583)


Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2024.3\plugins\intellij-csv-validator, version=4.0.1, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github/tracker, descriptorPath=intellij.vcs.github.tracker.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\plugins\vcs-github-ultimate, version=243.22562.180-ultimate, package=org.jetbrains.plugins.github.tasks, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github.ultimate/cron, descriptorPath=intellij.vcs.github.ultimate.cron.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\plugins\vcs-github-ultimate, version=243.22562.180-ultimate, package=com.intellij.vcs.github.ultimate.cron, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, moduleName=intellij.vcs.github.ultimate/docker, descriptorPath=intellij.vcs.github.ultimate.docker.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\plugins\vcs-github-ultimate, version=243.22562.180-ultimate, package=com.intellij.vcs.github.ultimate.action.runs.docker, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=GitHub, id=org.jetbrains.plugins.github, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\PyCharm 2023.3.4\plugins\vcs-github-ultimate, version=243.22562.180-ultimate, package=com.intellij.vcs.github.ultimate, isBundled=true), )

IDE
---
PyCharm (PY-243.22562.180)

**Comment by eyesee1** [comment]
Message
---
rescanning indexes of my project

Stacktrace
---
com.intellij.diagnostic.PluginException: Cannot check provider net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProviders$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:156)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:36)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:277)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:98)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:613)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:1189)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:778)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:765)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:189)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:157)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
	at java.base/java.lang.Thread.run(Thread.java:1583)


Plugin
---
PluginClassLoader(plugin=PluginMainDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, version=4.1.0, isBundled=false, path=~/Library/Application Support/JetBrains/PyCharm2025.2/plugins/intellij-csv-validator), packagePrefix=null, state=active, parents=ContentModuleDescriptor(moduleName=intellij.vcs.github.tracker, package=org.jetbrains.plugins.github.tasks) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), ContentModuleDescriptor(moduleName=intellij.vcs.github.json, package=org.jetbrains.plugins.github.json) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), ContentModuleDescriptor(moduleName=intellij.vcs.github.ultimate.docker, package=com.intellij.vcs.github.ultimate.docker) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), ContentModuleDescriptor(moduleName=intellij.vcs.github.ultimate.cron, package=com.intellij.vcs.github.ultimate.cron) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), ContentModuleDescriptor(moduleName=intellij.vcs.github.ultimate.features, package=com.intellij.vcs.github.ultimate) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), ContentModuleDescriptor(moduleName=intellij.relaxng) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.spellchecker) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.spellchecker.xml) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.platform.tasks) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.platform.tasks.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=252.27397.106, isBundled=true, path=~/Applications/PyCharm.app/Contents/lib), ContentModuleDescriptor(moduleName=intellij.vcs.github, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), ContentModuleDescriptor(moduleName=intellij.vcs.github.git) <- PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), PluginMainDescriptor(name=GitHub, id=org.jetbrains.plugins.github, version=252.27397.106-IU, isBundled=true, path=~/Applications/PyCharm.app/Contents/plugins/vcs-github-IU), )

IDE
---
PyCharm (PY-252.27397.106)
